### ISSUE TITLE
new ExpantaNum("J1.5") hangs the script

### ISSUE THREAD

**Issue by James103** [Naruyoko/ExpantaNum.js#13]
* The `1.5` in `new ExpantaNum("J1.5")` can be replaced by any positive decimal number and it will still result in a hang.
* The hang occurs in the `P.standardize` function.
* Reducing `ExpantaNum.maxOps` to 10 didn't help much.

**Comment by Naruyoko** [comment]
[α 1.3.6](https://github.com/Naruyoko/ExpantaNum.js/releases/tag/%CE%B1-1.3.6)

**Comment by James103** [comment]
I just tested, and it now rounds down any decimals after "J" to their previous integers before evaluating the result. This turns `J1.99999999` into `J1`, when it should be closer to `J2`.

**Comment by Naruyoko** [comment]
[α 1.3.7](https://github.com/Naruyoko/ExpantaNum.js/releases/tag/%CE%B1-1.3.7) - I changed it from floor to round, so `ExpantaNum("J1.99999999")` is now `(10^)^8 10000000000`=`J2`.

**Comment by James103** [comment]
That worked - `new ExpantaNum('J1.3276584').eq('J1')` and `new ExpantaNum('J1.9856349').eq('J2')` are both true.
