### ISSUE TITLE
i used factorial and toString() and got this result

### ISSUE THREAD

**Issue by Dragon77mathbye** [Naruyoko/ExpantaNum.js#15]
ExpantaNum(2).factorial.toString();
"function (){\n    var x=this.clone();\n    var f=ExpantaNum.factorials;\n    if (x.lt(ExpantaNum.ZERO)||!x.isint()) return x.add(1).gamma();\n    if (x.lte(170)) return new ExpantaNum(f[+x]);\n    var errorFixer=1;\n    var e=+x;\n    if (e<500) e+=163879/209018880*Math.pow(e,5);\n    if (e<1000) e+=-571/2488320*Math.pow(e,4);\n    if (e<50000) e+=-139/51840*Math.pow(e,3);\n    if (e<1e7) e+=1/288*Math.pow(e,2);\n    if (e<1e20) e+=1/12*e;\n    return x.div(ExpantaNum.E).pow(x).mul(x.mul(ExpantaNum.PI).mul(2).sqrt()).times(errorFixer);\n  }"

![image](https://user-images.githubusercontent.com/74103504/133089928-eca9de82-54f1-4675-97f7-42db426f9d05.png)

**Comment by Naruyoko** [comment]
You are missing `()` after `factorial`. Write `ExpantaNum(2).factorial().toString()`.

**Comment by Dragon77mathbye** [comment]
oh ok ty
