### ISSUE TITLE
Any way to perform hexation, heptation, ... with this?

### ISSUE THREAD

**Issue by Dragon77mathbye** [Naruyoko/ExpantaNum.js#16]
is there a function that I haven't seen that let's you use hyperoperations larger than tetration and pentation?

**Comment by James103** [comment]
Try using the following: `new OmegaNum(1).arrow(2)(3)` or `OmegaNum.arrow(1, 2, 3)`
1 = the base
2 = the hyperoperation (2 for tetration, 3 for pentation, 4 for hexation, 5 for heptation, etc)
3 = the number at the end

**Comment by Dragon77mathbye** [comment]
oh ok ty
