### ISSUE TITLE
Enter new ExpantaNum("10^^^^^^^10").toHyperE() make this freeze

### ISSUE THREAD

**Issue by 1e1000000** [Naruyoko/ExpantaNum.js#2]

**Comment by Naruyoko** [comment]
[α 1.3.2](https://github.com/Naruyoko/ExpantaNum.js/releases/tag/%CE%B1-1.3.2). Turns out the problem is that I put `mid=mid` instead of `min=mid`.

**Comment by 1e1000000** [comment]
fixed, enter new ExpantaNum("10^^^^^^^10").toHyperE() no longer freeze
10 nonation by 10
