### ISSUE TITLE
expantanum thinks that Genu's Number II is less than 10^^68 when it's not

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [Naruyoko/ExpantaNum.js#27]
code for https://naruyoko.github.io/ExpantaNum.js/test.html:
`let a = 1;
for (let b = 2; b <= 70; b++) {
    a = ExpantaNum.tetr(b,a);
}
return a < ExpantaNum.pent(10,68);`
Approximations of these values:
[Genu's Number II](https://googology.fandom.com/wiki/Genu%27s_number_II) ~ (10^^)^66 (10^)^25 153.90699754796802
10^^^68 = (10^^)^66 (10^)^8 10000000000
So clearly Genu's Number II > 10^^^68 but ExpantaNum thinks that Genu's Number II < 10^^^68

**Comment by Naruyoko** [comment]
To compare two `ExpantaNum` values, you need to use the `lt` method: `a.lt(ExpantaNum.pent(10,68))` or `ExpantaNum.lt(a,ExpantaNum.pent(10,68))`.

If you change your code to return the value of `a`, you will get `(10^^)^66 (10^)^25 153.90699754796802` as expected.
