### ISSUE TITLE
Enter ExpantaNum.pent() with base 0 output wrong

### ISSUE THREAD

**Issue by 1e1000000** [Naruyoko/ExpantaNum.js#3]
Input: ExpantaNum.pent(0,2) // 0^^^2
Output: NaN

Input: ExpantaNum.pent(0,Infinity) // 0^^^Infinity
Output: Infinity

**Comment by Naruyoko** [comment]
[α 1.3.3](https://github.com/Naruyoko/ExpantaNum.js/releases/tag/%CE%B1-1.3.3)

**Comment by 1e1000000** [comment]
fixed
