### ISSUE TITLE
Number probably have repeat item like (10^^)^22 "(10^)^75 (10^)^75" 153.15327796708874

### ISSUE THREAD

**Issue by 1e1000000** [Naruyoko/ExpantaNum.js#8]
This should be (10^^)^22 (10^)^150 153.15327796708874 for correct calculation or (10^^)^22 (10^)^75 153.15327796708874 for correct display

**Comment by Naruyoko** [comment]
ExpantaNum will automatically combine duplicate items.
```js
JSON.stringify(ExpantaNum("(10^^)^22 (10^)^75 (10^)^75 153.15327796708874").array)
  //"[[0,153.15327796708874],[1,150],[2,22]]"
JSON.stringify(ExpantaNum([[0,153],[1,75],[1,75],[2,22]]).array)
  //"[[0,153],[1,150],[2,22]]"
```

**Comment by 1e1000000** [comment]
return new ExpantaNum("(10^^)^12 (10^^)^19 (10^^)^8 (10^)^14 (10^)^18 (10^)^13 10^154");

(10^^)^39 (10^)^46 154

ok
